load nailgun aliases on server start
run-ng-server now calls loadChimeraNailgun.sh after starting
the server.

Also the classpath in run-ng-server was changed to
/usr/local/lib/*.jar [...] to include any version of
nailgun server and scala-librarty.

diff --git a/src/skel/usr/local/bin/run-ng-server b/src/skel/usr/local/bin/run-ng-server
--- a/src/skel/usr/local/bin/run-ng-server
+++ b/src/skel/usr/local/bin/run-ng-server
@@ -5,7 +5,7 @@ ng ng-version
 
 [ $? -eq 0 ] && echo "looks like nailgun server is running" && exit 1
 
-NG_CLASSPATH="/usr/local/lib/nailgun-server-0.9.2-SNAPSHOT.jar /usr/share/dcache/classes/* /usr/local/lib/scala-library.jar /usr/local/lib/ScalaChimeraNailgun"
+NG_CLASSPATH="/usr/local/lib/*.jar /usr/local/lib/ScalaChimeraNailgun /usr/share/dcache/classes/*"
     
 java -Dlog=warn -Dcom.sun.management.jmxremote.port=7778 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005 -jar /usr/local/lib/nailgun-server-0.9.2-SNAPSHOT.jar &
 
@@ -17,9 +17,19 @@ ng ng-cp $NG_CLASSPATH
 if [ $? -ne 0 ]; then
     echo "failed to start nailgun server"
     exit 2
-else
-    echo "server up and running"
-    exit 0
 fi
 
-exit 3
+echo "server up and running"
+
+sleep 3
+
+loadChimeraNailgun.sh
+
+if [ $? -ne 0 ]; then
+    echo "failed to set the nailgun aliases. "
+    echo "Try running loadChimeraNailgun.sh manually"
+    exit 3
+fi
+
+exit 0
+
